pipeline {

  agent any
  stages {
    stage('Build') {
      steps {
            bat 'mvn clean package deploy -DskipMunitTests -DmuleDeploy -DmuleVersion=4.4.0 -Dusername=Apisero259 -Dpassword=Apisero259 -DapplicationName=carbooking -Denvironment=Sandbox -DbusinessGroup="Apisero" -DworkerType=SMALL
      }
    }
	}
	
}