#%RAML 1.0 DataType
type: object
properties:
  Offer_Id : 
    type: integer
    required: true
    example: 1
  Offer: 
    type: string
    required: true
    example: Get 1000 OFF on bookings above 3 Months.
